#!/bin/bash

node_homepage="http://nodejs.org/download/"
node_bin="node"

[ -n "$1" ] && node_bin="$1"

error=""

local_version="$($node_bin -v 2>/dev/null)"
remote_version="$(wget -q -O - -- $node_homepage | grep 'Current version:' | sed -e 's/<[a-zA-Z\/][^>]*>//g' | sed 's/^ *//g' | sed 's/ $//g' | awk '{ print $3 }')"

if [ -z "$local_version" ]; then
  error="could not determine local node.js version"
  errcode=1
elif [ -z "$remote_version" ]; then
  error="could not determine remote node.js version"
  errcode=1
else
  if [ "$local_version" != "$remote_version" ]; then
    error="local node.js version is not up to date ($local_version vs. $remote_version)"
    errcode=2
  fi
fi

if [ "$error" != "" ]; then
  echo -e "ERROR: $error"
  exit $errcode
else
  echo "OK: local node.js version is up to date"
  exit 0
fi
